// (c) 2026 Timofey Ishimtsev.
// Licensed under PolyForm Small Business License 1.0.0

#include <gtest/gtest.h>
#include "../test_fixtures.h"

namespace delta::testing {

    /**
     * @class DeltaPathTest
     * @brief Tests for the DeltaPath class.
     *
     * DeltaPath manages a sequence of grids generated by applying a refinement
     * operator at each level. This suite checks basic refinement, invariants,
     * edge cases, and the behaviour with different strategies.
     */
    class DeltaPathTest : public DeltaTest {};

    /**
     * @test Verify that a dyadic path (midpoint operator) correctly refines
     *       the interval [0,1] for a simple function f(x)=x.
     *       After one step the grid should have three points (0, 1/2, 1) and
     *       the maximum gap should be 1/2. After two steps it should have five
     *       points and max gap 1/4.
     */
    TEST_F(DeltaPathTest, BasicDyadicPath) {
        ListGrid<Addr, Compare> grid0({ 0_r, 1_r });
        auto path = make_midpoint_path(grid0);

        auto func = [](const Addr& x) { return x; };

        path.advance(func);
        EXPECT_EQ(path.level(), 1);
        auto grid1 = path.current_grid();
        EXPECT_TRUE(is_sorted(grid1));
        EXPECT_TRUE(bounds_match(grid1, 0_r, 1_r));
        EXPECT_EQ(grid1.size(), 3);
        EXPECT_EQ(grid1[0], 0_r);
        EXPECT_EQ(grid1[1], 1_r / 2_r);
        EXPECT_EQ(grid1[2], 1_r);
        EXPECT_EQ(path.max_gap(), 1_r / 2_r);

        path.advance(func);
        EXPECT_EQ(path.level(), 2);
        auto grid2 = path.current_grid();
        EXPECT_TRUE(is_sorted(grid2));
        EXPECT_TRUE(bounds_match(grid2, 0_r, 1_r));
        EXPECT_EQ(grid2.size(), 5);
        EXPECT_EQ(grid2[0], 0_r);
        EXPECT_EQ(grid2[1], 1_r / 4_r);
        EXPECT_EQ(grid2[2], 1_r / 2_r);
        EXPECT_EQ(grid2[3], 3_r / 4_r);
        EXPECT_EQ(grid2[4], 1_r);
        EXPECT_EQ(path.max_gap(), 1_r / 4_r);
    }

    /**
     * @test Constructing a path with an empty grid should succeed,
     *       and the path should have level 0 and an empty grid.
     */
    TEST_F(DeltaPathTest, ConstructWithEmptyGrid) {
        ListGrid<Addr, Compare> empty_grid;
        auto strategy = make_midpoint_strategy();
        auto path = make_path(empty_grid, std::move(strategy));
        EXPECT_EQ(path.level(), 0);
        EXPECT_EQ(path.current_grid().size(), 0);
    }

    /**
     * @test Constructing a path with a single‑element grid should succeed,
     *       and the grid should contain that single address.
     */
    TEST_F(DeltaPathTest, ConstructWithSingleElementGrid) {
        ListGrid<Addr, Compare> grid({ 42_r });
        auto strategy = make_midpoint_strategy();
        auto path = make_path(grid, std::move(strategy));
        EXPECT_EQ(path.level(), 0);
        EXPECT_EQ(path.current_grid().size(), 1);
        EXPECT_EQ(path.current_grid()[0], 42_r);
    }

    /**
     * @test Advancing on an empty grid does nothing (the grid stays empty)
     *       but the level counter is incremented.
     */
    TEST_F(DeltaPathTest, AdvanceOnEmptyGrid) {
        ListGrid<Addr, Compare> empty_grid;
        auto strategy = make_midpoint_strategy();
        auto path = make_path(empty_grid, std::move(strategy));
        auto func = [](const Addr&) { return Val(0); };
        path.advance(func);
        EXPECT_EQ(path.level(), 1);
        EXPECT_EQ(path.current_grid().size(), 0);
    }

    /**
     * @test Advancing on a single‑element grid does nothing (the grid stays
     *       unchanged) but the level counter is incremented.
     */
    TEST_F(DeltaPathTest, AdvanceOnSingleElementGrid) {
        ListGrid<Addr, Compare> grid({ 42_r });
        auto strategy = make_midpoint_strategy();
        auto path = make_path(grid, std::move(strategy));
        auto func = [](const Addr&) { return Val(0); };
        path.advance(func);
        EXPECT_EQ(path.level(), 1);
        EXPECT_EQ(path.current_grid().size(), 1);
        EXPECT_EQ(path.current_grid()[0], 42_r);
    }

    /**
     * @test max_gap() returns the largest distance between consecutive addresses
     *       according to the metric. For a non‑uniform grid it should be correct.
     */
    TEST_F(DeltaPathTest, MaxGap) {
        ListGrid<Addr, Compare> grid({ 0_r, 2_r, 5_r, 10_r });
        auto strategy = make_midpoint_strategy();
        auto path = make_path(grid, std::move(strategy));
        EXPECT_EQ(path.max_gap(), 5_r);
    }

    /**
     * @test max_gap() on an empty grid returns zero.
     */
    TEST_F(DeltaPathTest, MaxGapEmpty) {
        ListGrid<Addr, Compare> empty_grid;
        auto strategy = make_midpoint_strategy();
        auto path = make_path(empty_grid, std::move(strategy));
        EXPECT_EQ(path.max_gap(), 0_r);
    }

    /**
     * @test max_gap() on a single‑element grid returns zero.
     */
    TEST_F(DeltaPathTest, MaxGapSingle) {
        ListGrid<Addr, Compare> grid({ 42_r });
        auto strategy = make_midpoint_strategy();
        auto path = make_path(grid, std::move(strategy));
        EXPECT_EQ(path.max_gap(), 0_r);
    }

    /**
     * @test After each refinement, the grid must remain sorted and its bounds
     *       must stay the same as the original bounds.
     */
    TEST_F(DeltaPathTest, InvariantsAfterAdvance) {
        ListGrid<Addr, Compare> grid({ 0_r, 1_r });
        auto path = make_midpoint_path(grid);
        auto func = [](const Addr& x) { return x; };

        for (int i = 0; i < 5; ++i) {
            path.advance(func);
            EXPECT_TRUE(is_sorted(path.current_grid()));
            EXPECT_TRUE(bounds_match(path.current_grid(), 0_r, 1_r));
        }
    }

    /**
     * @test Using a fixed‑lambda operator (λ = 1/3) should place new points
     *       at one‑third of the interval instead of the midpoint.
     */
    TEST_F(DeltaPathTest, FixedLambda) {
        ListGrid<Addr, Compare> grid({ 0_r, 1_r });
        auto strategy = make_lambda_strategy(1_r / 3_r);
        auto path = make_path(grid, std::move(strategy));
        auto func = [](const Addr& x) { return x; };
        path.advance(func);
        auto g = path.current_grid();
        EXPECT_EQ(g.size(), 3);
        EXPECT_EQ(g[0], 0_r);
        EXPECT_EQ(g[1], 1_r / 3_r);
        EXPECT_EQ(g[2], 1_r);
    }

    /**
     * @test A dynamic strategy that changes the operator per level should
     *       produce the expected points (first level uses λ=1/3, second level
     *       uses λ=2/3 on the sub‑intervals).
     */
    TEST_F(DeltaPathTest, DynamicStrategy) {
        ListGrid<Addr, Compare> grid({ 0_r, 1_r });
        FixedLambdaOperator op13(1_r / 3_r);
        FixedLambdaOperator op23(2_r / 3_r);
        std::vector<FixedLambdaOperator> ops = { op13, op23 };
        auto strategy = make_dynamic_strategy(ops);
        auto path = make_path(grid, std::move(strategy));
        auto func = [](const Addr& x) { return x; };

        path.advance(func);
        auto g1 = path.current_grid();
        EXPECT_EQ(g1[1], 1_r / 3_r);

        path.advance(func);
        auto g2 = path.current_grid();
        EXPECT_EQ(g2.size(), 5);
        EXPECT_EQ(g2[0], 0_r);
        EXPECT_EQ(g2[1], 2_r / 9_r);
        EXPECT_EQ(g2[2], 1_r / 3_r);
        EXPECT_EQ(g2[3], 7_r / 9_r);
        EXPECT_EQ(g2[4], 1_r);
    }

    /**
     * @test When value caching is disabled (DELTA_USE_CACHING=0), the path
     *       should still refine correctly. This test temporarily undefines
     *       the macro and restores it afterwards.
     */
    TEST_F(DeltaPathTest, NoCaching) {
#ifdef DELTA_USE_CACHING
#undef DELTA_USE_CACHING
#define DELTA_USE_CACHING 0
#endif
        ListGrid<Addr, Compare> grid({ 0_r, 1_r });
        auto path = make_midpoint_path(grid);
        auto func = [](const Addr& x) { return x; };
        for (int i = 0; i < 5; ++i) {
            path.advance(func);
            EXPECT_TRUE(is_sorted(path.current_grid()));
        }
#ifdef DELTA_USE_CACHING
#undef DELTA_USE_CACHING
#define DELTA_USE_CACHING 1
#endif
    }

#ifdef _OPENMP
    /**
     * @test If OpenMP is enabled, the path should still work (no crashes,
     *       and the grid remains sorted after refinements).
     */
    TEST_F(DeltaPathTest, OpenMP) {
        ListGrid<Addr, Compare> grid({ 0_r, 1_r });
        auto path = make_midpoint_path(grid);
        auto func = [](const Addr& x) { return x; };
        for (int i = 0; i < 5; ++i) {
            path.advance(func);
        }
    }
#endif

    /**
     * @test Many refinements (12 levels) with a quadratic function.
     *       The grid size should become large (>1000 points), remain sorted,
     *       and keep the original bounds.
     */
    TEST_F(DeltaPathTest, ManyRefinements) {
        ListGrid<Addr, Compare> grid({ 0_r, 1_r });
        auto path = make_midpoint_path(grid);
        auto func = [](const Addr& x) { return x * x; };
        const int N = 12;
        for (int i = 0; i < N; ++i) {
            path.advance(func);
        }
        EXPECT_EQ(path.level(), N);
        EXPECT_GT(path.current_grid().size(), 1000);
        EXPECT_TRUE(is_sorted(path.current_grid()));
        EXPECT_TRUE(bounds_match(path.current_grid(), 0_r, 1_r));
    }

} // namespace delta::testing